repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  gwt_user: com.google.gwt:gwt-user:jar:2.8.1
