repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
